# Generated by Django 3.2.15 on 2022-10-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='ajeetdb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=20, null=True, unique=True)),
                ('Last_name', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
